main:
  - identifier: posts
    name: Blog
    url: /articles/
    weight: 1
  - identifier: about
    name: Sobre mi
    url: /pages/about
    weight: 2
  - identifier: resume
    name: CV
    url: /resume/
    weight: 3
  - identifier: uses
    name: Que uso
    url: /pages/uses
    weight: 4
