main:
  - identifier: posts
    name: Blog
    url: /articles/
    weight: 1
  - identifier: about
    name: About me
    url: /page/about
    weight: 2
  - identifier: resume
    name: Resume
    url: /resume
    weight: 3
  - identifier: uses
    name: Uses
    url: /page/uses
    weight: 4
